# For more information: https://laravel.com/docs/sail
version: '3'
services:
  course-app:
    build: .
    ports:
      - "8081:80"
    volumes:
        - ./:/usr/share/nginx



  
          # - selenium
  # selenium:
  #     image: 'selenium/standalone-chrome'
  #     volumes:
  #         - '/dev/shm:/dev/shm'
  #     networks:
  #         - sail
  #     depends_on:
  #         - laravel.test
  mysql:
      image: 'mysql:8.0'
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
          - 'sailmysql:/var/lib/mysql'
      networks:
          - sail
  redis:
      image: 'redis:alpine'
      ports:
          - '${FORWARD_REDIS_PORT:-6379}:6379'
      volumes:
          - 'sailredis:/data'
      networks:
          - sail
  # memcached:
  #     image: 'memcached:alpine'
  #     ports:
  #         - '11211:11211'
  #     networks:
  #         - sail
  mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
          - 1025:1025
          - 8025:8025
      networks:
          - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
